### ISSUE TITLE
Get error with select.paramenter with discrete data 

### ISSUE THREAD

**Issue by LucasMS** [itsrainingdata/sparsebn#10]
Error:
```
> param=select.parameter(current.learn, current.data)
 Error in eval(expr, envir, enclos) : object 'Anti' not found
```

This error only appears when the input dataset of sparsebnData() is a matrix. I observed it with discrete data. The error does not occur when the input dataset of sparsebnData() is a data.frame.

Maybe send warning while not using data.frame with sparsebnData()?

**Comment by bryonaragam** [comment]
Thanks for the report! Can you please provide sample code to reproduce this error? It looks like there is an issue with an object named `Anti`, which I don't recognize...

**Comment by LucasMS** [comment]
I couldn't reproduce the error. Should be fine. Sorry for the false alarm :/
