### ISSUE TITLE
#Fucntion to_igraph not converting network to graph?

### ISSUE THREAD

**Issue by LucasMS** [itsrainingdata/sparsebn#11]
```

> library(sparsebn)
> library(igraph)
> cyto.data <- sparsebnData(cytometryContinuous[["data"]],
+                           type = "continuous",
+                           ivn = cytometryContinuous[["ivn"]])
> cyto.learn <- estimate.dag(data = cyto.data)
> cyto.param <- estimate.parameters(cyto.learn, data = cyto.data)
> param=select.parameter(cyto.learn, cyto.data)
> 
> 
> cyto.learn.igraph=to_igraph(cyto.learn[[param ]])
> 
> get.edges(cyto.learn.igraph)
Error in ends(graph, es, names = FALSE) : Not a graph object
```

**Comment by bryonaragam** [comment]
This is intended behaviour, but its a bit confusing so I'll try to explain:

`cyto.learn` is a list containing `sparsebnFit` objects. These objects are _not_ graphs, they contain the graph data plus a bunch of other metadata (see `?sparsebnFit`). The graph data is in the `edges` slot of a `sparsebnFit` object.

When you call `to_igraph` (or `to_graphNEL`, etc.) on a `sparsebnFit` object, the graph data gets converted, but the output is still of class `sparsebnFit`. If you call `to_igraph` on an graph object directly, then the output will be an `igraph` object.

Maybe this is confusing behaviour... I may consider changing this if I see more confusion arise :-)

Here are two ways to fix this code:

```
cyto.learn.igraph=to_igraph(cyto.learn[[param]]$edges) # pull out the graph data to begin with
get.edges(cyto.learn.igraph)
```

or

```
cyto.learn.igraph=to_igraph(cyto.learn[[param]]) # keep the metadata
get.edges(cyto.learn.igraph$edges) # pull out the graph data here instead
```

Note that in both you cases you still need to specify the `es` argument to `igraph::get.edges` (see `?get.edges`).

**Comment by bryonaragam** [comment]
The documentation on this is very unclear -- need to update this with a more clear description of how these methods work.
