### ISSUE TITLE
Need to add an argument in estimate.dag function

### ISSUE THREAD

**Issue by gujyjean** [itsrainingdata/sparsebn#2]
In cd.run() function, I added an argument: adaptive
It used to be:
cd.run <- function(indata, weights=NULL, lambdas=NULL, lambdas.length=30, error.tol=0.0001, convLb=0.01, weight.scale=1.0, upperbound = 100.0) {...}

And now I updated it as:
cd.run <- function(indata, weights=NULL, lambdas=NULL, lambdas.length=30, error.tol=0.0001, convLb=0.01, weight.scale=1.0, upperbound = 100.0, adaptive = FALSE) {...}

Jiaying

**Comment by bryonaragam** [comment]
Fixed by 1631c06.
